### ISSUE TITLE
Wordpress 5.9 not working properly

### ISSUE THREAD

**Issue by fubeco** [thallysondias/wp-booking-engine#1]
The plugin install just fine, but the text can not be seen from website page. The engine works fine. The only text to be seen is the calendar. Unfortunately can not be used in the website.

**Comment by thallysondias** [comment]
hey @fubeco i update just now the plugin.
Can you test again?

**Comment by fubeco** [comment]
Thank you very much Thailyson, but I don't use omnibees anymore. I just change this month from Omnibees to Hsystem.
I really appreciate your effort and hope others can use it.
Sincerely,
Fulvio
    Em quinta-feira, 16 de junho de 2022 05:53:24 BRT, Thallyson dias ***@***.***> escreveu:  
 
 


Closed #1 as completed.
